name: CI Metal for v3

on:
  workflow_dispatch:

jobs:
  macOS-metal-build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'v3'

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Dependencies
        run: |
          brew install cmake

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install requests

      - name: Configure + Build
        run: python -m scripts.build_all

      - name: Upload Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -m scripts.upload_all --tag v3.0.0 --repo rbertus2000/sdkit
